language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --dev
  - cp phpunit.xml.dist phpunit.xml
  - php -v

script:
  - phpunit

notifications:
  email: false
