language: php

php:
  - 5.3
  - 5.4
  - 5.5

notifications:
  email: false

env:
  - DB=mysql CAKE_VERSION=master
  - DB=mysql CAKE_VERSION=2.4
  - DB=sqlite CAKE_VERSION=master
  - DB=sqlite CAKE_VERSION=2.4
  - DB=pgsql CAKE_VERSION=master
  - DB=pgsql CAKE_VERSION=2.4

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test2;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test3;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE SCHEMA test2;' -U postgres -d cakephp_test; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE SCHEMA test3;' -U postgres -d cakephp_test; fi"

  - set +H

  - cd ..
  - git clone git://github.com/cakephp/cakephp.git cakephp --branch $CAKE_VERSION --depth 1
  - cd cakephp
  - chmod -R 777 app/tmp
  - mv ../cakephp-crud app/Plugin/Crud
  - mv app/Plugin/Crud/.resources/database.php app/Config/database.php
  - mv app/Plugin/Crud/.resources/phpunit.xml.dist phpunit.xml.dist
  - mv app/Plugin/Crud/.resources/composer.json composer.json
  - composer install --dev --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - ./lib/Cake/Console/cake test Crud AllCrud --stderr --coverage-clover build/logs/clover.xml --configuration phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
