url: "http://localhost:4000"
github_url: "https://github.com/jippi/cakephp-crud/blob/develop"
api_url: "http://cakephp.dk/cakephp-crud/develop"
pygments: true
safe: true
timezone: UTC
destination: "_local"
